services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omani_therapist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/tmp:/app/tmp
    env_file:
      - ./backend/.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  pgdata:
