services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omani_therapist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/tmp:/app/tmp
    environment:
      - OPENAI_API_KEY=your_openai_key
      - CLAUDE_API_KEY=your_claude_key
      - GOOGLE_API_KEY=your_google_key
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/omani_therapist
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  pgdata:
